// first of all we need to export an object path contains products as a property and products its an array of products
// /**this object conatins product and product its an array */
//     /**Prdoduct will be described ad id */
//     This is the first product what i am going to do is to deprecate this product 
 export default {
    products: [
        {
            _id: '1',
            name: 'Men Regular Fit Checkered Button Down Collar Casual Shirt',
            category: 'Shirts',
            image: '/images/product-1.webp',
            price: 1559,
            brand: 'U.S. POLO ASSN.',
            rating: 4,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'BLUE LINE Men Slim Fit Self Design Spread Collar Casual Shirt',
            category: 'Shirts',
            image: '/images/product-2.webp',
            price: 1799,
            brand: 'LOUIS PHILIPPE',
            rating: 4,
            numReviews: 50,
            countInStock: 6,
        },
        {
            _id: '3',
            name: ' Men Regular Fit Color Block Spread Collar Casual Shirt',
            category: 'Shirts',
            image: '/images/product-3.webp',
            price: 3749,
            brand: 'TOMMY HILFIGER',
            rating: 5,
            numReviews: 60,
            countInStock: 6,
        },
        {
            _id: '4',
            name: 'Men Slim Fit Striped Spread Collar Casual Shirt',
            category: 'Shirts',
            image: '/images/product-4.webp',
            price: 1349,
            brand: 'PETER ENGLAND',
            rating: 3,
            numReviews: 70,
            countInStock: 6,
        },
        {
            _id: '5',
            name: 'HOLIDAY Men Solid Polo Neck Brown T-Shirt',
            category: 'Tshirt',
            image: '/images/product-5.webp',
            price: 799,
            brand: 'Louis Philippe Sports',
            rating: 4,
            numReviews: 55,
            countInStock: 6,
        },
        {
            _id: '6',
            name: 'Men Striped V Neck White T-Shirt',
            category: 'Tshirt',
            image: '/images/product-6.webp',
            price: 599,
            brand: 'PETER ENGLAND',
            rating: 4.5,
            numReviews: 55,
            countInStock: 6,
        },
        {
            _id: '7',
            name: 'Men Solid Polo Neck Black T-Shirt',
            category: 'Tshirt',
            image: '/images/product-7.webp',
            price: 2799,
            brand: 'TOMMY HILFIGER',
            rating: 5,
            numReviews: 85,
            countInStock: 6,
        },
        {
            _id: '8',
            name: 'Men Solid Polo Neck Black T-Shirt',
            category: 'Tshirt',
            image: '/images/product-8.webp',
            price: 824,
            brand: 'U.S. POLO ASSN.',
            rating: 5,
            numReviews: 75,
            countInStock: 6,
        },
        {
            _id: '9',
            name: 'Men Slim Mid Rise Blue Jeans',
            category: 'Pants',
            image: '/images/product-9.webp',
            price: 2039,
            brand: 'WROGN ',
            rating: 4.5,
            numReviews: 55,
            countInStock: 6,
        },
        {
            _id: '10',
            name: 'Men Jogger Fit Mid Rise Dark Blue Jeans',
            category: 'Pants',
            image: '/images/product-10.webp',
            price: 1919,
            brand: 'WROGN ',
            rating: 3,
            numReviews: 55,
            countInStock: 6,
        },
        {
            _id: '11',
            name: 'Men Slim Mid Rise Black Jeans',
            category: 'Pants',
            image: '/images/product-11.webp',
            price: 2039,
            brand: 'U.S. POLO ASSN.',
            rating: 4.5,
            numReviews: 65,
            countInStock: 6,
        },
        {
            _id: '12',
            name: 'Men Slim Mid Rise Green Jeans',
            category: 'Pants',
            image: '/images/product-12.webp',
            price: 2698,
            brand: 'U.S. POLO ASSN.',
            rating: 4.5,
            numReviews: 55,
            countInStock: 6,
        },
        {
            _id: '13',
            name: ' Club Sneakers For Men  (Black)',
            category: 'Shoes',
            image: '/images/product-13.webp',
            price: 2879,
            brand: 'PUMA',
            rating: 4.5,
            numReviews: 75,
            countInStock: 6,
        },
        {
            _id: '14',
            name: 'Sneakers For Men  (Beige)',
            category: 'Shoes',
            image: '/images/product-14.webp',
            price: 1848,
            brand: 'WOODLAND',
            rating: 3,
            numReviews: 75,
            countInStock: 6,
        },
        {
            _id: '15',
            name: 'NK COURT VISION LO NN Sneakers For Men  (Black)',
            category: 'Shoes',
            image: '/images/product-15.webp',
            price: 3996,
            brand: 'NIKE',
            rating: 3.5,
            numReviews: 75,
            countInStock: 6,
        },
        {
            _id: '16',
            name: 'Ferrari Track Racer Sneakers For Men  (White)',
            category: 'Shoes',
            image: '/images/product-16.webp',
            price: 3899,
            brand: 'PUMA',
            rating: 4.5,
            numReviews: 75,
            countInStock: 6,
        },
        {
            _id: '17',
            name: 'FS5851 Bronson Analog Watch - For Men',
            category: 'Watch',
            image: '/images/product-17.webp',
            price: 7849,
            brand: 'FOSSIL',
            rating: 5,
            numReviews: 39,
            countInStock: 6,
        },
        {
            _id: '18',
            name: 'CH2601 DECKER Analog Watch - For Men',
            category: 'Watch',
            image: '/images/product-18.webp',
            price: 6599,
            brand: 'FOSSIL',
            rating: 5,
            numReviews: 59,
            countInStock: 6,
        },
        {
            _id: '19',
            name: 'NP1730SL02 Analog Watch - For Men',
            category: 'Watch',
            image: '/images/product-19.webp',
            price: 2495,
            brand: ' Titan ',
            rating: 4,
            numReviews: 49,
            countInStock: 6,
        },
        {
            _id: '20',
            name: 'FS5268I GRANT SPOR Analog Watch - For Men',
            category: 'Watch',
            image: '/images/product-20.webp',
            price: 6597,
            brand: 'FOSSIL',
            rating: 5,
            numReviews: 99,
            countInStock: 6,
        },
    ],
};